addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml
      - libcups2-dev # for aeroo
      - wkhtmltopdf # for odoo pdf reports (tested on sale for eg.)

language: python
sudo: false
cache: pip

python:
  - "2.7"

env:
  global:
  - VERSION="8.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='jjscarafia'
  - TRANSIFEX_ORGANIZATION='adhoc'
  # to get secure, run 'travis encrypt TRANSIFEX_PASSWORD=[transifex_password] -r [github_repo]'
  # example of github repo 'ingadhoc/odoo-infrastructure'
  - secure: znz/SSupt0Srn+J1SF2V4nRYEGlx3nOh6BscNth0iv5VNdLoGxMreOfZJ4GVtv9N7rPb/469ApBtV/L+mHJyumd18f8BAszsjkMSjWst5MnfuijX0emm2i1gHZOP9lHKKCv3fN5bCubizBN6+cwQ84+kCeqzf6v9qDOVjByRpI3n8N+iYU5yBhh7VjzhVGWj761j5vMUJI72jT0iFRwVnebfefKh9w8gYPyKgddW4cqNPChNXkiWSZAw7qBvU2ElMI6gGZCBFOoKBj2Gy6mcXap5ZDssPRZsnH11sop9wYZ573Rf1UFZNlc9IQUaDnagojaGjWEnIFjVO4uxZJpAgDBz7MIYT7nYWbsBu2q3bYWGJ9I3tozSyJ/lXkLm9q6nVQ5o8LI6BzFQkPukupVExIVQ285Ag/cc28gxCX7L8ANfKUyfzUszaqXaeTS4klLQERaBY1CdCbheNGDpXAFKq2avukCdGzJ99NTaIFKCCM5RP1wE/AysrkHZSArUmGm+ABRNQJ4LsDdOPHwb+1QTaXjiPRpYFPDb35vb0mF3dPSAUG4zd9BsjZzy8EAdfg8EMx6YzuZWHi3wPzbWDuNBc/ErfVSJBLcJHAGol7loMUVT+307xh8P64xU1D0f+BuzoI7JdM0Nj99uaiSjsgIyDMFBiL01I1BNweqmt7AKNuM=
  # exlcude because:
    # we dont want odoo argentina time penalty
      # account_interests
      # inter_company_move
      # sale_other_product_description
    # incompatibility with account_analytic_accounts:
      # account_move_analytic
    # we exclude partner_state because it gives an error and we could not find why
    # incompatibility with website_sale:
      # product_variant_imp
    # depreceated and gives error:
      # product_cost_currency
  - EXCLUDE="product_catalog_aeroo_report_public_categ,product_website_categ_search,partner_state,product_variant_imp,product_cost_currency,inter_company_move,account_interests,sale_other_product_description,account_move_analytic"
  # dummy " for better formatting

  matrix:
  # TODO enable lint check
  #- LINT_CHECK="1"
  - TRANSIFEX="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"

virtualenv:
  system_site_packages: true

install:
  # aeroo reports
  - pip install git+https://github.com/aeroo/aeroolib.git@master pycups==1.9.68

  # repository requirements
  - pip install -r requirements.txt

  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
